apiVersion: v1
kind: Service
metadata:
  name: kafka-service-hd
  namespace: default
spec:
  ports:
    - nodePort: 30000
      port: 30000
      protocol: TCP
      targetPort: 9092
  selector:
    #statefulset.kubernetes.io/pod-name: kafka-0
    app: kafka
  type: NodePort